import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import RequireAuth from '../src/components/RequireAuth';
import LoadingView from '../src/components/LoadingView';
import MessageBox from '../src/components/MessageBox';
import { useAuth } from '../src/context/AuthContext';
import { useTheme } from '../src/context/ThemeContext';
import { api, getApiError } from '../src/services/api';

export default function DashboardScreen(){return <RequireAuth><Dashboard/></RequireAuth>}
function Dashboard(){
 const {user,logout}=useAuth();const {colors,mode,toggleTheme}=useTheme();const {width}=useWindowDimensions();const desktop=width>=960;
 const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{setError('');try{const r=await api.get('/dashboard');setData(r.data);}catch(e){setError(await getApiError(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 if(loading)return <View style={[styles.loading,{backgroundColor:colors.background}]}><LoadingView label="Loading dashboard..."/></View>;
 const employee=data?.employee||{};
 const employeeActions=[['Attendance','location-outline','/attendance',colors.primarySoft,colors.primary],['Apply Leave','calendar-outline','/leave',colors.roseSoft,colors.rose],['Attendance History','bar-chart-outline','/history',colors.lilacSoft,colors.lilac],['Profile','person-outline','/profile',colors.goldSoft,colors.gold]];
 const managerActions=[['Leave Approvals','checkmark-done-outline','/management',colors.primarySoft,colors.primary],['Apply Leave','calendar-outline','/leave',colors.roseSoft,colors.rose],['Notifications','notifications-outline','/notifications',colors.lilacSoft,colors.lilac],['Profile','person-outline','/profile',colors.goldSoft,colors.gold]];
 const headActions=[['Leave Approvals','checkmark-done-outline','/management',colors.primarySoft,colors.primary],['Apply Leave','calendar-outline','/leave',colors.roseSoft,colors.rose],['Organization Admin','settings-outline','/admin',colors.lilacSoft,colors.lilac],['Notifications','notifications-outline','/notifications',colors.secondarySoft||colors.roseSoft,colors.secondary||colors.rose],['Profile','person-outline','/profile',colors.goldSoft,colors.gold]];
 const actions=user.role==='EMPLOYEE'?employeeActions:user.role==='MANAGER'?managerActions:headActions;
 const doLogout=async()=>{await logout();router.replace('/login');};
 return <View style={[styles.page,{backgroundColor:colors.background}]}>{desktop&&<View style={[styles.sidebar,{backgroundColor:colors.primary}]}><View><View style={styles.brand}><Ionicons name="people-circle-outline" size={34} color="#fff"/><Text style={styles.brandText}>Dev Portal</Text></View>{[['Dashboard','grid-outline','/dashboard'],...actions.map(a=>[a[0],a[1],a[2]])].map(([t,i,r])=><Pressable key={t} onPress={()=>router.push(r)} style={[styles.sideItem,t==='Dashboard'&&styles.sideActive]}><Ionicons name={i} size={20} color="#fff"/><Text style={styles.sideText}>{t}</Text></Pressable>)}</View><Text style={styles.sideFoot}>Attendance • Leave • Teams</Text></View>}
 <View style={styles.main}><View style={[styles.topbar,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><View><Text style={[styles.topTitle,{color:colors.text}]}>Dashboard</Text><Text style={{color:colors.muted,fontSize:12}}>{employee.name||user.name}</Text></View><View style={styles.topRight}><Pressable onPress={()=>router.push('/notifications')} style={[styles.iconBtn,{borderColor:colors.border}]}><Ionicons name="notifications-outline" size={20} color={colors.text}/>{data?.unreadNotifications>0&&<View style={[styles.badge,{backgroundColor:colors.danger}]}><Text style={styles.badgeText}>{data.unreadNotifications}</Text></View>}</Pressable><Pressable onPress={toggleTheme} style={[styles.iconBtn,{borderColor:colors.border}]}><Ionicons name={mode==='dark'?'sunny-outline':'moon-outline'} size={20} color={colors.text}/></Pressable><Pressable onPress={doLogout} style={[styles.logout,{borderColor:colors.border}]}><Text style={{color:colors.danger,fontWeight:'900'}}>Logout</Text></Pressable></View></View>
 <ScrollView contentContainerStyle={styles.content}><View style={styles.inner}>{!!error&&<MessageBox type="danger">{error}</MessageBox>}<View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.eyebrow,{color:colors.primary}]}>WELCOME BACK</Text><Text style={[styles.hello,{color:colors.text}]}>Hello, {employee.name||user.name}! 👋</Text><Text style={[styles.meta,{color:colors.muted}]}>{employee.employeeId} · {String(employee.role||user.role).replaceAll('_',' ')} · {employee.jobTitle||'Team member'}</Text><Text style={[styles.desc,{color:colors.muted}]}>Your organization, attendance and leave activity in one place.</Text><View style={styles.pills}>{[employee.department,employee.team,employee.supervisorName&&`Reports to ${employee.supervisorName}`].filter(Boolean).map(x=><View key={x} style={[styles.pill,{backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}><Text style={{color:colors.text,fontWeight:'700',fontSize:12}}>{x}</Text></View>)}</View></View><View style={[styles.heroIcon,{backgroundColor:colors.primarySoft}]}><Ionicons name="briefcase-outline" size={45} color={colors.primary}/></View></View>
 <View style={styles.stats}>{user.role==='EMPLOYEE'&&<Stat title="Today's Attendance" value={data?.todayAttendance?.status||'NOT CHECKED IN'} icon="time-outline" colors={colors}/>}<Stat title="Available Leave" value={`${employee.availableLeaveDays??0} days`} icon="briefcase-outline" colors={colors}/>{user.role!=='EMPLOYEE'&&<Stat title="Role" value={user.role.replaceAll('_',' ')} icon="shield-checkmark-outline" colors={colors}/>}<Stat title="Team / Section" value={employee.team||'—'} icon="git-network-outline" colors={colors}/></View>
 <View><Text style={[styles.section,{color:colors.text}]}>{user.role==='EMPLOYEE'?'Employee actions':user.role==='MANAGER'?'Manager actions':'Head Manager actions'}</Text><Text style={{color:colors.muted,marginTop:4}}>Only actions allowed for your role are shown.</Text></View><View style={styles.grid}>{actions.map(([t,i,r,b,c])=><Pressable key={t} onPress={()=>router.push(r)} style={({pressed})=>[styles.card,{backgroundColor:colors.surface,borderColor:colors.border,opacity:pressed?.78:1}]}><View style={[styles.actionIcon,{backgroundColor:b}]}><Ionicons name={i} size={25} color={c}/></View><Text style={[styles.cardTitle,{color:colors.text}]}>{t}</Text><Text style={{color:colors.muted,lineHeight:20}}>{t==='Leave Approvals'?'Review employee leave requests. First Manager/Head decision is final.':t==='Organization Admin'?'Create, assign and reassign company accounts, departments and teams.':`Open ${t.toLowerCase()}.`}</Text></Pressable>)}</View></View></ScrollView></View></View>;
}
function Stat({title,value,icon,colors}){return <View style={[styles.stat,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.statIcon,{backgroundColor:colors.primarySoft}]}><Ionicons name={icon} size={23} color={colors.primary}/></View><View style={{flex:1}}><Text style={{color:colors.muted,fontSize:12,fontWeight:'700'}}>{title}</Text><Text style={{color:colors.text,fontWeight:'900',fontSize:19,marginTop:4,textTransform:'capitalize'}}>{value}</Text></View></View>}
const styles=StyleSheet.create({page:{flex:1,flexDirection:'row'},loading:{flex:1},sidebar:{width:245,padding:20,justifyContent:'space-between'},brand:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:28,padding:8},brandText:{color:'#fff',fontSize:20,fontWeight:'900'},sideItem:{flexDirection:'row',alignItems:'center',gap:12,padding:13,borderRadius:12,marginBottom:6},sideActive:{backgroundColor:'rgba(255,255,255,.16)'},sideText:{color:'#fff',fontWeight:'700'},sideFoot:{color:'rgba(255,255,255,.72)',fontSize:11},main:{flex:1},topbar:{minHeight:72,borderBottomWidth:1,paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},topTitle:{fontWeight:'900',fontSize:21},topRight:{flexDirection:'row',gap:8,alignItems:'center'},iconBtn:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},badge:{position:'absolute',top:-4,right:-4,minWidth:18,height:18,borderRadius:9,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontSize:10,fontWeight:'900'},logout:{height:42,paddingHorizontal:14,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},content:{padding:22,paddingBottom:48},inner:{maxWidth:1220,width:'100%',alignSelf:'center',gap:18},hero:{borderWidth:1,borderRadius:24,padding:28,flexDirection:'row',alignItems:'center',gap:20},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2},hello:{fontSize:32,fontWeight:'900',marginTop:8},meta:{marginTop:7,fontWeight:'700',textTransform:'capitalize'},desc:{marginTop:10,fontSize:15},heroIcon:{width:108,height:108,borderRadius:30,alignItems:'center',justifyContent:'center'},pills:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:18},pill:{borderWidth:1,paddingHorizontal:11,paddingVertical:7,borderRadius:999},stats:{flexDirection:'row',flexWrap:'wrap',gap:12},stat:{flex:1,minWidth:220,borderWidth:1,borderRadius:18,padding:17,flexDirection:'row',alignItems:'center',gap:13},statIcon:{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center'},section:{fontSize:20,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{flexGrow:1,flexBasis:230,minHeight:150,borderWidth:1,borderRadius:18,padding:18,gap:9},actionIcon:{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:16,fontWeight:'900'}});
