import 'dotenv/config';
import path from 'path';
import cors from 'cors';
import express from 'express';
import authRoutes from './routes/auth.routes.js';
import attendanceRoutes from './routes/attendance.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import leaveRoutes from './routes/leave.routes.js';
import managementRoutes from './routes/management.routes.js';
import assistRoutes from './routes/assist.routes.js';
import profileRoutes from './routes/profile.routes.js';
import organizationRoutes from './routes/organization.routes.js';
import notificationsRoutes from './routes/notifications.routes.js';
import { errorHandler, notFound } from './middleware/error.js';

if (!process.env.JWT_SECRET) throw new Error('JWT_SECRET is missing. Copy .env.example to .env and set a secret.');
const app = express(); const port = Number(process.env.PORT || 4000);
app.use(cors({ origin: process.env.CLIENT_ORIGIN === '*' ? true : process.env.CLIENT_ORIGIN }));
app.use(express.json({ limit: '2mb' }));
app.use('/uploads', express.static(path.resolve('uploads')));
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'employee-portal-api' }));
app.use('/api/auth', authRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/attendance', attendanceRoutes);
app.use('/api/leaves', leaveRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api/assist', assistRoutes);
app.use('/api/management', managementRoutes);
app.use('/api/organization', organizationRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use(notFound); app.use(errorHandler);
app.listen(port, () => console.log(`Employee Portal API listening on http://localhost:${port}`));
